node_compat = true
name = "bazk-api"
main = "dist/index.mjs"
compatibility_date = "2024-03-25"

[durable_objects]
bindings = [{ name = "DURABLE", class_name = "Intermediary" }]

[[migrations]]
tag = "v1"
new_classes = ["Intermediary"]

[build]
command = "node build.js"

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
